# Generated by Django 5.2.14 on 2026-05-26 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JuniorHighSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='No')),
                ('name', models.CharField(max_length=100, verbose_name='学校名')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='市町村')),
                ('principal_name', models.CharField(blank=True, max_length=50, verbose_name='校長名')),
                ('tel', models.CharField(blank=True, max_length=30, verbose_name='電話番号')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
                ('third_grade_total', models.IntegerField(default=0, verbose_name='3年合計')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '中学校情報',
                'verbose_name_plural': '中学校情報',
                'ordering': ['number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JuniorHighClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, verbose_name='クラス名')),
                ('boys', models.IntegerField(default=0, verbose_name='男子')),
                ('girls', models.IntegerField(default=0, verbose_name='女子')),
                ('total', models.IntegerField(default=0, verbose_name='計')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='publicity.juniorhighschool', verbose_name='中学校')),
            ],
            options={
                'verbose_name': '中学校クラス人数',
                'verbose_name_plural': '中学校クラス人数',
                'ordering': ['school__number', 'id'],
            },
        ),
    ]
