# Generated by Django 5.2.14 on 2026-07-22 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.PositiveIntegerField(unique=True, verbose_name='職員番号')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='職名')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('assignment', models.CharField(blank=True, max_length=150, verbose_name='担任・校務')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='教科')),
                ('responsibility', models.CharField(blank=True, max_length=200, verbose_name='役職・主任')),
                ('club', models.CharField(blank=True, max_length=100, verbose_name='顧問部活動')),
                ('is_active', models.BooleanField(default=True, verbose_name='在籍中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicity_teacher', to=settings.AUTH_USER_MODEL, verbose_name='ログインユーザー')),
            ],
            options={
                'verbose_name': '教員',
                'verbose_name_plural': '教員',
                'ordering': ['employee_number'],
            },
        ),
        migrations.CreateModel(
            name='TeacherLoginEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ログイン用メールアドレス')),
                ('email_type', models.CharField(choices=[('school', '学校用'), ('personal', '個人用'), ('other', 'その他')], default='school', max_length=20, verbose_name='メール種別')),
                ('is_allowed', models.BooleanField(default=True, verbose_name='ログインを許可する')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主メールアドレス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_emails', to='publicity.teacher', verbose_name='教員')),
            ],
            options={
                'verbose_name': '教員ログイン用メール',
                'verbose_name_plural': '教員ログイン用メール',
                'ordering': ['teacher__employee_number', 'email_type'],
            },
        ),
    ]
