# Generated by Django 5.2.14 on 2026-07-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0002_teacher_teacherloginemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('club_advisor', '部活動顧問'), ('publicity_admin', '広報管理者'), ('system_admin', 'システム管理者')], default='club_advisor', max_length=30, verbose_name='システム権限'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='氏名'),
        ),
    ]
