# Generated by Django 5.2.14 on 2026-07-29 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0003_teacher_role_alter_teacher_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='部活動名')),
                ('is_active', models.BooleanField(default=True, verbose_name='使用中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '部活動',
                'verbose_name_plural': '部活動',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='奨学金区分名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='使用中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '奨学金区分',
                'verbose_name_plural': '奨学金区分',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProspectiveStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('postal_code', models.CharField(blank=True, help_text='例：886-0001', max_length=8, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('assigned_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_prospective_students', to='publicity.teacher', verbose_name='担当教員')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospective_students', to='publicity.club', verbose_name='部活動')),
                ('junior_high_school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prospective_students', to='publicity.juniorhighschool', verbose_name='中学校')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_prospective_students', to='publicity.teacher', verbose_name='登録者')),
                ('scholarship_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospective_students', to='publicity.scholarshipcategory', verbose_name='奨学金区分')),
            ],
            options={
                'verbose_name': '募集対象生徒',
                'verbose_name_plural': '募集対象生徒',
                'ordering': ['-created_at', 'name'],
            },
        ),
    ]
