# Generated by Django 5.2.14 on 2026-07-29 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0004_club_scholarshipcategory_prospectivestudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='送付方法')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '送付方法',
                'verbose_name_plural': '送付方法',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='書類名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='使用中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '書類種類',
                'verbose_name_plural': '書類種類',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateField(verbose_name='送付日')),
                ('memo', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicity.deliverymethod', verbose_name='送付方法')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicity.teacher', verbose_name='送付担当')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_histories', to='publicity.prospectivestudent', verbose_name='対象生徒')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicity.documenttype', verbose_name='書類種類')),
            ],
            options={
                'verbose_name': '送付履歴',
                'verbose_name_plural': '送付履歴',
                'ordering': ['-sent_date', '-created_at'],
            },
        ),
    ]
