# Generated by Django 5.2.14 on 2026-07-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0005_deliverymethod_documenttype_documenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectivestudent',
            name='dormitory',
            field=models.BooleanField(default=False, verbose_name='寮希望'),
        ),
        migrations.AddField(
            model_name='prospectivestudent',
            name='name_kana',
            field=models.CharField(blank=True, max_length=100, verbose_name='ふりがな'),
        ),
    ]
