# Generated by Django 5.2.14 on 2026-07-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0006_prospectivestudent_dormitory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juniorhighclass',
            name='establishment_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='設置区分'),
        ),
        migrations.AddField(
            model_name='juniorhighclass',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='使用中'),
        ),
        migrations.AddField(
            model_name='juniorhighclass',
            name='is_from_mext',
            field=models.BooleanField(default=False, verbose_name='文科省データ'),
        ),
        migrations.AddField(
            model_name='juniorhighclass',
            name='official_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='学校所在地'),
        ),
        migrations.AddField(
            model_name='juniorhighclass',
            name='official_postal_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='学校郵便番号'),
        ),
        migrations.AddField(
            model_name='juniorhighclass',
            name='prefecture',
            field=models.CharField(blank=True, max_length=20, verbose_name='都道府県'),
        ),
        migrations.AddField(
            model_name='juniorhighclass',
            name='school_code',
            field=models.CharField(blank=True, help_text='文部科学省が付与する13桁の学校コード', max_length=13, null=True, unique=True, verbose_name='学校コード'),
        ),
        migrations.AddField(
            model_name='juniorhighclass',
            name='school_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='学校種'),
        ),
    ]
