# Generated by Django 5.2.14 on 2026-08-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0008_remove_juniorhighclass_establishment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectivestudent',
            name='junior_high_loan_scholarship_applied',
            field=models.BooleanField(default=False, verbose_name='中学3年時申込可能な貸与型奨学金に申込済み'),
        ),
        migrations.AddField(
            model_name='prospectivestudent',
            name='scholarship_wanted',
            field=models.BooleanField(default=False, verbose_name='奨学金希望'),
        ),
    ]
