# Generated by Django 5.2.14 on 2026-08-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0009_prospectivestudent_junior_high_loan_scholarship_applied_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(help_text='例：2026', unique=True, verbose_name='年度（西暦）')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='最終発行番号')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '文書番号管理',
                'verbose_name_plural': '文書番号管理',
                'ordering': ['-fiscal_year'],
            },
        ),
    ]
