# Generated by Django 5.2.14 on 2026-08-18 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0010_documentnumbersequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(verbose_name='年度（西暦）')),
                ('document_number', models.CharField(max_length=50, unique=True, verbose_name='文書番号')),
                ('issue_date', models.DateField(verbose_name='発行日')),
                ('seasonal_greeting', models.CharField(max_length=50, verbose_name='時候の挨拶')),
                ('principal_name', models.CharField(max_length=100, verbose_name='校長名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_scholarship_request_documents', to='publicity.teacher', verbose_name='作成者')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_request_documents', to='publicity.juniorhighschool', verbose_name='送付先中学校')),
                ('students', models.ManyToManyField(related_name='scholarship_request_documents', to='publicity.prospectivestudent', verbose_name='対象生徒')),
            ],
            options={
                'verbose_name': '奨学生募集依頼文書',
                'verbose_name_plural': '奨学生募集依頼文書',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
