# Generated by Django 5.2.14 on 2026-08-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0011_scholarshiprequestdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshiprequestdocument',
            name='status',
            field=models.CharField(choices=[('issued', '発行済'), ('cancelled', '取消')], default='issued', max_length=20, verbose_name='状態'),
        ),
    ]
