# Generated by Django 5.2.14 on 2026-08-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0012_scholarshiprequestdocument_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshiprequestdocument',
            name='document_number',
            field=models.CharField(max_length=50, verbose_name='文書番号'),
        ),
    ]
