# Generated by Django 5.2.14 on 2026-08-19 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0013_alter_scholarshiprequestdocument_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshiprequestdocument',
            name='corrected_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrected_documents', to='publicity.scholarshiprequestdocument', verbose_name='訂正元文書'),
        ),
        migrations.AddField(
            model_name='scholarshiprequestdocument',
            name='correction_reason',
            field=models.TextField(blank=True, verbose_name='訂正理由'),
        ),
        migrations.AlterField(
            model_name='scholarshiprequestdocument',
            name='status',
            field=models.CharField(choices=[('issued', '発行済'), ('corrected', '訂正済み'), ('cancelled', '取消')], default='issued', max_length=20, verbose_name='状態'),
        ),
    ]
