# Generated by Django 5.2.14 on 2026-08-21 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0014_scholarshiprequestdocument_corrected_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '未対応'), ('rank_set', 'ランク設定済'), ('interview_scheduled', '面談予定'), ('interviewed', '面談済'), ('temporary_accepted', '仮承諾済'), ('adjusting', 'ランク調整中'), ('conference_confirmed', '連絡会確認済'), ('finalized', '最終確定'), ('accepted', '正式承諾'), ('declined', '辞退')], default='not_started', max_length=30, verbose_name='進行状況')),
                ('temporary_accepted', models.BooleanField(default=False, verbose_name='面談時仮承諾')),
                ('temporary_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='仮承諾日時')),
                ('final_accepted', models.BooleanField(default=False, verbose_name='正式承諾')),
                ('final_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='正式承諾日時')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='最終確定日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('current_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_assignments', to='publicity.scholarshipcategory', verbose_name='現在ランク')),
                ('final_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_assignments', to='publicity.scholarshipcategory', verbose_name='最終確定ランク')),
                ('interview_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interview_assignments', to='publicity.scholarshipcategory', verbose_name='面談時ランク')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_assignment', to='publicity.prospectivestudent', verbose_name='対象生徒')),
            ],
            options={
                'verbose_name': '奨学生候補管理',
                'verbose_name_plural': '奨学生候補管理',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='面談予定日時')),
                ('interviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='面談実施日時')),
                ('result', models.CharField(choices=[('pending', '未実施'), ('temporary_accepted', '仮承諾'), ('considering', '検討中'), ('declined', '辞退')], default='pending', max_length=30, verbose_name='面談結果')),
                ('notes', models.TextField(blank=True, verbose_name='面談記録・備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='publicity.scholarshipassignment', verbose_name='奨学生候補')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_interviews', to='publicity.teacher', verbose_name='面談担当者')),
                ('presented_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='publicity.scholarshipcategory', verbose_name='面談時提示ランク')),
            ],
            options={
                'verbose_name': '奨学生面談',
                'verbose_name_plural': '奨学生面談',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipRankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='変更理由')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='変更日時')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_histories', to='publicity.scholarshipassignment', verbose_name='奨学生候補')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_rank_changes', to='publicity.teacher', verbose_name='変更者')),
                ('new_rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='publicity.scholarshipcategory', verbose_name='変更後ランク')),
                ('previous_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='publicity.scholarshipcategory', verbose_name='変更前ランク')),
            ],
            options={
                'verbose_name': '奨学生ランク変更履歴',
                'verbose_name_plural': '奨学生ランク変更履歴',
                'ordering': ['-changed_at'],
            },
        ),
    ]
