# Generated by Django 5.2.14 on 2026-08-21 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0015_scholarshipassignment_scholarshipinterview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormitoryBenefitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='寮費区分名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='使用中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '寮費区分',
                'verbose_name_plural': '寮費区分',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='scholarshipassignment',
            name='current_dormitory_benefit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_assignments', to='publicity.dormitorybenefitcategory', verbose_name='現在寮費区分'),
        ),
        migrations.AddField(
            model_name='scholarshipassignment',
            name='final_dormitory_benefit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_assignments', to='publicity.dormitorybenefitcategory', verbose_name='最終確定寮費区分'),
        ),
        migrations.AddField(
            model_name='scholarshipassignment',
            name='interview_dormitory_benefit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interview_assignments', to='publicity.dormitorybenefitcategory', verbose_name='面談時寮費区分'),
        ),
        migrations.AddField(
            model_name='scholarshipinterview',
            name='presented_dormitory_benefit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='publicity.dormitorybenefitcategory', verbose_name='面談時提示寮費区分'),
        ),
        migrations.CreateModel(
            name='DormitoryBenefitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='変更理由')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='変更日時')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dormitory_benefit_histories', to='publicity.scholarshipassignment', verbose_name='奨学生候補')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dormitory_benefit_changes', to='publicity.teacher', verbose_name='変更者')),
                ('new_benefit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='publicity.dormitorybenefitcategory', verbose_name='変更後寮費区分')),
                ('previous_benefit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='publicity.dormitorybenefitcategory', verbose_name='変更前寮費区分')),
            ],
            options={
                'verbose_name': '寮費区分変更履歴',
                'verbose_name_plural': '寮費区分変更履歴',
                'ordering': ['-changed_at'],
            },
        ),
    ]
