# Generated by Django 5.2.14 on 2026-08-22 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0016_dormitorybenefitcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(help_text='例：2027', verbose_name='年度（西暦）')),
                ('quota', models.PositiveIntegerField(default=0, verbose_name='上限人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_quotas', to='publicity.scholarshipcategory', verbose_name='奨学金区分')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_quotas', to='publicity.club', verbose_name='部活動')),
            ],
            options={
                'verbose_name': '奨学生枠',
                'verbose_name_plural': '奨学生枠',
                'ordering': ['-fiscal_year', 'club__name', 'category__name'],
                'constraints': [models.UniqueConstraint(fields=('fiscal_year', 'club', 'category'), name='unique_scholarship_quota')],
            },
        ),
    ]
