# Generated by Django 5.2.14 on 2026-08-22 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0017_scholarshipquota'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormitoryBenefitQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(help_text='例：2027', verbose_name='年度（西暦）')),
                ('quota', models.PositiveIntegerField(default=0, verbose_name='上限人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dormitory_benefit_quotas', to='publicity.dormitorybenefitcategory', verbose_name='寮費区分')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dormitory_benefit_quotas', to='publicity.club', verbose_name='部活動')),
            ],
            options={
                'verbose_name': '寮費待遇枠',
                'verbose_name_plural': '寮費待遇枠',
                'ordering': ['-fiscal_year', 'club__name', 'benefit__name'],
                'constraints': [models.UniqueConstraint(fields=('fiscal_year', 'club', 'benefit'), name='unique_dormitory_benefit_quota')],
            },
        ),
    ]
