# Generated by Django 5.2.14 on 2026-08-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0018_dormitorybenefitquota'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshiprequestdocument',
            name='recruitment_year',
            field=models.CharField(blank=True, help_text='例：令和9年度', max_length=20, verbose_name='募集年度'),
        ),
    ]
