# Generated by Django 5.2.14 on 2026-08-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0019_scholarshiprequestdocument_recruitment_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectivestudent',
            name='advisor_response',
            field=models.CharField(choices=[('not_confirmed', '未確認'), ('waiting', '確認中'), ('accept', '面談する'), ('decline', '面談しない')], default='not_confirmed', max_length=20, verbose_name='部顧問返答'),
        ),
        migrations.AddField(
            model_name='prospectivestudent',
            name='advisor_response_memo',
            field=models.TextField(blank=True, verbose_name='部顧問返答メモ'),
        ),
        migrations.AddField(
            model_name='prospectivestudent',
            name='contact_date',
            field=models.DateField(blank=True, null=True, verbose_name='中学校連絡日'),
        ),
        migrations.AddField(
            model_name='prospectivestudent',
            name='contact_memo',
            field=models.TextField(blank=True, verbose_name='中学校からの連絡内容'),
        ),
        migrations.AddField(
            model_name='prospectivestudent',
            name='contact_status',
            field=models.CharField(choices=[('not_contacted', '未連絡'), ('contacted', '連絡済'), ('waiting', '返答待ち'), ('responded', '返答あり')], default='not_contacted', max_length=20, verbose_name='中学校連絡状況'),
        ),
        migrations.AddField(
            model_name='prospectivestudent',
            name='interview_date',
            field=models.DateField(blank=True, null=True, verbose_name='面談日'),
        ),
        migrations.AddField(
            model_name='prospectivestudent',
            name='interview_memo',
            field=models.TextField(blank=True, verbose_name='面談メモ'),
        ),
        migrations.AddField(
            model_name='prospectivestudent',
            name='interview_result',
            field=models.CharField(choices=[('undecided', '未判定'), ('considering', '継続検討'), ('candidate', '奨学生候補'), ('declined', '見送り')], default='undecided', max_length=20, verbose_name='面談結果'),
        ),
        migrations.AddField(
            model_name='prospectivestudent',
            name='interview_status',
            field=models.CharField(choices=[('not_decided', '未確認'), ('scheduled', '面談予定'), ('completed', '面談済'), ('declined', '面談なし')], default='not_decided', max_length=20, verbose_name='面談状況'),
        ),
        migrations.AddField(
            model_name='prospectivestudent',
            name='management_memo',
            field=models.TextField(blank=True, verbose_name='管理職メモ'),
        ),
    ]
