# Generated by Django 5.2.14 on 2026-08-27 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0020_prospectivestudent_advisor_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipShippingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_type', models.CharField(choices=[('mail', '郵送'), ('hand_delivery', '持参'), ('resend', '再発送')], default='mail', max_length=20, verbose_name='発送方法')),
                ('shipping_order', models.PositiveIntegerField(blank=True, null=True, verbose_name='発送順')),
                ('is_shipped', models.BooleanField(default=False, verbose_name='発送済み')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='発送日時')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='発送メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_shipping_records', to='publicity.teacher', verbose_name='登録者')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_records', to='publicity.scholarshiprequestdocument', verbose_name='発行文書')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_shipping_records', to='publicity.prospectivestudent', verbose_name='対象生徒')),
            ],
            options={
                'verbose_name': '奨学生文書発送履歴',
                'verbose_name_plural': '奨学生文書発送履歴',
                'ordering': ['shipping_order', 'student__junior_high_school__prefecture', 'student__junior_high_school__city', 'student__junior_high_school__name', 'student__name'],
            },
        ),
    ]
