# Generated by Django 5.2.14 on 2026-09-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0021_scholarshipshippingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshiprequestdocument',
            name='document_type',
            field=models.CharField(choices=[('normal', '通常募集依頼'), ('name_correction', '氏名訂正・お詫び')], default='normal', max_length=30, verbose_name='文書種類'),
        ),
    ]
