# Generated by Django 5.2.14 on 2026-09-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0022_scholarshiprequestdocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshiprequestdocument',
            name='display_date_text',
            field=models.CharField(blank=True, max_length=30, verbose_name='文書表示日付'),
        ),
    ]
