# Generated by Django 5.2.14 on 2026-10-03 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('circulating', '回覧中'), ('approved', '校長承認済'), ('returned', '差戻し'), ('cancelled', '取消')], default='draft', max_length=20, verbose_name='状態')),
                ('destination_area', models.CharField(max_length=200, verbose_name='用務地')),
                ('destination_name', models.CharField(blank=True, max_length=200, verbose_name='施設・会場名')),
                ('purpose', models.TextField(verbose_name='用務')),
                ('start_datetime', models.DateTimeField(verbose_name='出張開始日時')),
                ('end_datetime', models.DateTimeField(verbose_name='出張終了日時')),
                ('departure_place', models.CharField(choices=[('school', '学校'), ('home', '自宅'), ('other', 'その他')], default='school', max_length=20, verbose_name='出発地')),
                ('departure_place_other', models.CharField(blank=True, max_length=200, verbose_name='その他の出発地')),
                ('transportation', models.CharField(choices=[('private_car', '自家用車'), ('ride', '同乗'), ('school_car', '校用車'), ('microbus', 'マイクロバス'), ('large_bus', '大型バス'), ('public', '公共交通機関'), ('other', 'その他')], max_length=30, verbose_name='交通手段')),
                ('transportation_other', models.CharField(blank=True, max_length=200, verbose_name='その他の交通手段')),
                ('separate_travel_expense', models.BooleanField(default=False, verbose_name='旅費別途支給')),
                ('use_toll_road', models.BooleanField(default=False, verbose_name='有料道路使用希望')),
                ('use_etc', models.BooleanField(default=False, verbose_name='ETC使用希望')),
                ('is_holiday_trip', models.BooleanField(default=False, verbose_name='休業日の出張')),
                ('take_substitute_holiday', models.BooleanField(default=False, verbose_name='振替休日を取得する')),
                ('substitute_holiday_date', models.DateField(blank=True, null=True, verbose_name='振替休日取得予定日')),
                ('no_substitute_holiday_reason', models.TextField(blank=True, verbose_name='振替休日を取得しない理由')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='回覧申請日時')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='校長承認日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_travel_orders', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_travel_orders', to=settings.AUTH_USER_MODEL, verbose_name='責任者')),
            ],
            options={
                'verbose_name': '旅行命令',
                'verbose_name_plural': '旅行命令',
                'ordering': ['-start_datetime', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelClassAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='月日')),
                ('period', models.PositiveSmallIntegerField(verbose_name='校時')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='科')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='学年')),
                ('class_name', models.CharField(blank=True, max_length=50, verbose_name='組')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='科目')),
                ('substitute_teacher', models.CharField(blank=True, max_length=100, verbose_name='代行')),
                ('travel_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_adjustments', to='documents.travelorder', verbose_name='旅行命令')),
            ],
            options={
                'verbose_name': '旅行命令 授業処置',
                'verbose_name_plural': '旅行命令 授業処置',
                'ordering': ['date', 'period'],
            },
        ),
        migrations.CreateModel(
            name='TravelAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='travel_orders/%Y/%m/', verbose_name='添付ファイル')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='元ファイル名')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_attachments', to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
                ('travel_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.travelorder', verbose_name='旅行命令')),
            ],
            options={
                'verbose_name': '旅行命令 添付資料',
                'verbose_name_plural': '旅行命令 添付資料',
            },
        ),
        migrations.CreateModel(
            name='TravelCompanion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_companions', to=settings.AUTH_USER_MODEL, verbose_name='同行者')),
                ('travel_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companions', to='documents.travelorder', verbose_name='旅行命令')),
            ],
            options={
                'verbose_name': '旅行同行者',
                'verbose_name_plural': '旅行同行者',
                'constraints': [models.UniqueConstraint(fields=('travel_order', 'teacher'), name='unique_travel_order_companion')],
            },
        ),
    ]
