# Generated by Django 5.2.14 on 2026-10-04 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('publicity', '0023_scholarshiprequestdocument_display_date_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelorder',
            name='responsible_person',
        ),
        migrations.AddField(
            model_name='travelorder',
            name='responsible_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_travel_orders', to='publicity.teacher', verbose_name='責任者'),
        ),
        migrations.AlterField(
            model_name='travelcompanion',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_companions', to='publicity.teacher', verbose_name='同行者'),
        ),
    ]
