# Generated by Django 5.2.14 on 2026-10-04 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_travelorder_responsible_person_and_more'),
        ('publicity', '0023_scholarshiprequestdocument_display_date_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelorder',
            name='responsible_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_travel_orders', to='publicity.teacher', verbose_name='責任者'),
        ),
    ]
