# Generated by Django 5.2.14 on 2026-10-04 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_travelorder_responsible_teacher'),
        ('publicity', '0023_scholarshiprequestdocument_display_date_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', '申請'), ('approved', '承認'), ('returned', '差戻し'), ('resubmitted', '再申請'), ('cancelled', '取消')], max_length=20, verbose_name='操作')),
                ('step_order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='回覧順')),
                ('comment', models.TextField(blank=True, verbose_name='コメント・差戻し理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作日時')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_approval_histories', to=settings.AUTH_USER_MODEL, verbose_name='操作ユーザー')),
                ('actor_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='travel_approval_histories', to='publicity.teacher', verbose_name='操作教員')),
                ('travel_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_histories', to='documents.travelorder', verbose_name='旅行命令')),
            ],
            options={
                'verbose_name': '旅行命令 回覧履歴',
                'verbose_name_plural': '旅行命令 回覧履歴',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TravelApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveSmallIntegerField(verbose_name='回覧順')),
                ('status', models.CharField(choices=[('waiting', '待機中'), ('pending', '確認待ち'), ('approved', '承認済'), ('returned', '差戻し')], default='waiting', max_length=20, verbose_name='状態')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='差戻し日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_approval_steps', to='publicity.teacher', verbose_name='承認者')),
                ('travel_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='documents.travelorder', verbose_name='旅行命令')),
            ],
            options={
                'verbose_name': '旅行命令 回覧者',
                'verbose_name_plural': '旅行命令 回覧者',
                'ordering': ['travel_order', 'step_order'],
                'constraints': [models.UniqueConstraint(fields=('travel_order', 'step_order'), name='unique_travel_approval_step_order'), models.UniqueConstraint(fields=('travel_order', 'approver'), name='unique_travel_approval_approver')],
            },
        ),
    ]
